name: Sn
version: '${project.version}'
main: sn.sn.Sn
api-version: 1.18

commands:
  express:
    #描述这个命令
    description: 雪花速递~
    #用法
    usage: /express help
    #执行此命令的人所需的权限
    permission:
      sn.express.basicio
    #没有权限的提示消息
    permission-message: 你不能执行它.
  quest:
    #描述这个命令
    description: 雪夜任务系统~
    #用法
    usage: /quest help
    #执行此命令的人所需的权限
    permission:
      sn.quest.basicio
    #没有权限的提示消息
    permission-message: 你不能执行它.

permission:
  sn.express.basicio:
    description: 雪花速递的基本输入输出权限
    default: true
  sn.express.admin:
    description: 雪花速递的管理员权限
    default: op
  sn.quest.basicio:
    description: 雪夜任务系统的基本权限
    default: true
  sn.quest.admin:
    description: 雪夜任务系统的管理员权限
    default: op

